export const instructions = [
  {
    "mnem": "ADD",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 0,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "ADD",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 1,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "INT",
    "dst": { "a": "I", "t": "b" },
    "src": { "a": "F", "t": "v" },
    "opcode": 0xCD,
    "modifier": "i",
    "definition": "i",
  },
  {
    "mnem": "DEC",
    "dst": { "a": "Z", "t": "v" },
    "opcode": 48,
    "modifier": "oszap",
    "definition": "oszap",
  },
  {
    "mnem": "PUSH",
    "dst": { "a": "E", "t": "v" },
    "opcode": 0xFF,
    "rm0": 6,
    "modifier": "",
    "definition": "",
  },
  {
    "mnem": "POp",
    "dst": { "a": "E", "t": "v" },
    "opcode": 0x8F,
    "rm0": 0,
    "modifier": "",
    "definition": "",
  },
  {
    "mnem": "DEC",
    "dst": { "a": "E", "t": "b" },
    "opcode": 0xFE,
    "rm0": 1,
    "modifier": "oszap",
    "definition": "oszap",
  },
  {
    "mnem": "DEC",
    "dst": { "a": "E", "t": "vqp" },
    "opcode": 0xFF,
    "rm0": 1,
    "modifier": "oszap",
    "definition": "oszap",
  },
  {
    "mnem": "INC",
    "dst": { "a": "Z", "t": "v" },
    "opcode": 40,
    "modifier": "oszap",
    "definition": "oszap",
  },
  {
    "mnem": "INC",
    "dst": { "a": "E", "t": "b" },
    "opcode": 0xFE,
    "rm0": 0,
    "modifier": "oszap",
    "definition": "oszap",
  },
  {
    "mnem": "INC",
    "dst": { "a": "E", "t": "vqp" },
    "opcode": 0xFF,
    "rm0": 0,
    "modifier": "oszap",
    "definition": "oszap",
  },
  {
    "mnem": "ADD",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 2,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "ADD",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 3,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "OR",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 8,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "OR",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 9,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "OR",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 10,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "OR",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 11,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "ADC",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 16,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "ADC",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 17,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "ADC",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 18,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "ADC",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 19,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SBB",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 24,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SBB",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 25,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SBB",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 26,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SBB",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 27,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "AND",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 32,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "AND",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 33,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "AND",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 34,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "AND",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 35,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "SUB",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 40,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SUB",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 41,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SUB",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 42,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "SUB",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 43,
    "modifier": "oszapc",
    "definition": "oszapc",
  },
  {
    "mnem": "XOR",
    "dst": { "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 48,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "XOR",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 49,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "XOR",
    "dst": { "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 50,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  {
    "mnem": "XOR",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 51,
    "modifier": "oszapc",
    "definition": "oszpc",
    "undefinition": "a",
  },
  { "mnem": "JO", "src": { "a": "J", "t": "bs" }, "opcode": 112 },
  { "mnem": "JNO", "src": { "a": "J", "t": "bs" }, "opcode": 113 },
  { "mnem": "JS", "src": { "a": "J", "t": "bs" }, "opcode": 120 },
  { "mnem": "JNS", "src": { "a": "J", "t": "bs" }, "opcode": 121 },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "E", "t": "b" },
    "src": { "a": "G", "t": "b" },
    "opcode": 136,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 137,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "G", "t": "b" },
    "src": { "a": "E", "t": "b" },
    "opcode": 138,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 139,
  },
  {
    "mnem": "LEA",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "@depend": "no", "a": "M" },
    "opcode": 141,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "S", "t": "w" },
    "src": { "a": "E", "t": "w" },
    "opcode": 142,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "Z", "t": "b" },
    "src": { "a": "I", "t": "b" },
    "opcode": 176,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "Z", "t": "vqp" },
    "src": { "a": "I", "t": "vqp" },
    "opcode": 184,
  },
  {
    "mnem": "RETN",
    "src": { "@address": "SC", "@displayed": "no", "#text": "SS:[rSP]" },
    "#comment": "1.02",
    "opcode": 195,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "E", "t": "b" },
    "src": { "a": "I", "t": "b" },
    "opcode": 198,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "E", "t": "vqp" },
    "src": { "a": "I", "t": "vds" },
    "opcode": 199,
  },
  {
    "mnem": "RETF",
    "src": { "@address": "SC", "@displayed": "no", "#text": "SS:[rSP]" },
    "#comment": "1.02",
    "opcode": 203,
  },
  { "mnem": "JMP", "src": { "a": "J", "t": "vds" }, "opcode": 233 },
  { "mnem": "JMP", "src": { "a": "J", "t": "bs" }, "opcode": 235 },
  {
    "mnem": "VERR",
    "src": { "a": "E", "t": "w" },
    "opcode": 0,
    "sinceExtension": "SSE3",
    "modifier": "z",
    "definition": "z",
    "isTwoByte": true,
  },
  {
    "mnem": "VERW",
    "src": { "a": "E", "t": "w" },
    "opcode": 0,
    "sinceExtension": "SSSE3",
    "modifier": "z",
    "definition": "z",
    "isTwoByte": true,
  },
  { "mnem": "JMPE", "opcode": 0, "sinceExtension": "SSE41", "isTwoByte": true },
  {
    "mnem": "VMCALL",
    "opcode": 1,
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "VMLAUNCH",
    "opcode": 1,
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "VMRESUME",
    "opcode": 1,
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "VMXOFF",
    "opcode": 1,
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "INVLPG",
    "src": { "@depend": "no", "a": "M" },
    "opcode": 1,
    "sinceExtension": "SSE42",
    "isTwoByte": true,
  },
  { "mnem": "INVD", "opcode": 8, "isTwoByte": true },
  { "mnem": "WBINVD", "opcode": 9, "isTwoByte": true },
  { "mnem": "UD2", "opcode": 11, "isTwoByte": true },
  {
    "mnem": "NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 13,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVUPS",
    "dst": { "@depend": "no", "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 16,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSS",
    "dst": { "@depend": "no", "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 16,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVUPD",
    "dst": { "@depend": "no", "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 16,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSD",
    "dst": { "@depend": "no", "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 16,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVUPS",
    "dst": { "@depend": "no", "a": "W", "t": "ps" },
    "src": { "a": "V", "t": "ps" },
    "opcode": 17,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSS",
    "dst": { "@depend": "no", "a": "W", "t": "ss" },
    "src": { "a": "V", "t": "ss" },
    "opcode": 17,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVUPD",
    "dst": { "@depend": "no", "a": "W", "t": "pd" },
    "src": { "a": "V", "t": "pd" },
    "opcode": 17,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSD",
    "dst": { "@depend": "no", "a": "W", "t": "sd" },
    "src": { "a": "V", "t": "sd" },
    "opcode": 17,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVHLPS",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "U", "t": "q" },
    "opcode": 18,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVLPS",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "M", "t": "q" },
    "opcode": 18,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVLPD",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "M", "t": "q" },
    "opcode": 18,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVDDUP",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "W", "t": "q" },
    "opcode": 18,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSLDUP",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "W", "t": "q" },
    "opcode": 18,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVLPS",
    "dst": { "@depend": "no", "a": "M", "t": "q" },
    "src": { "a": "V", "t": "q" },
    "opcode": 19,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVLPD",
    "dst": { "@depend": "no", "a": "M", "t": "q" },
    "src": { "a": "V", "t": "q" },
    "opcode": 19,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "UNPCKLPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "q" },
    "opcode": 20,
    "isTwoByte": true,
  },
  {
    "mnem": "UNPCKLPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 20,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "UNPCKHPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "q" },
    "opcode": 21,
    "isTwoByte": true,
  },
  {
    "mnem": "UNPCKHPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 21,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVLHPS",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "U", "t": "q" },
    "opcode": 22,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVHPS",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "M", "t": "q" },
    "opcode": 22,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVHPD",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "M", "t": "q" },
    "opcode": 22,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSHDUP",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "W", "t": "q" },
    "opcode": 22,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVHPS",
    "dst": { "@depend": "no", "a": "M", "t": "q" },
    "src": { "a": "V", "t": "q" },
    "opcode": 23,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVHPD",
    "dst": { "@depend": "no", "a": "M", "t": "q" },
    "src": { "a": "V", "t": "q" },
    "opcode": 23,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 24,
    "isTwoByte": true,
  },
  {
    "mnem": "PREFETCHNTA",
    "src": { "@depend": "no", "a": "M", "t": "b" },
    "opcode": 24,
    "isTwoByte": true,
  },
  {
    "mnem": "PREFETCHT0",
    "src": { "@depend": "no", "a": "M", "t": "b" },
    "opcode": 24,
    "sinceExtension": "MMX",
    "isTwoByte": true,
  },
  {
    "mnem": "PREFETCHT1",
    "src": { "@depend": "no", "a": "M", "t": "b" },
    "opcode": 24,
    "sinceExtension": "SSE1",
    "isTwoByte": true,
  },
  {
    "mnem": "PREFETCHT2",
    "src": { "@depend": "no", "a": "M", "t": "b" },
    "opcode": 24,
    "sinceExtension": "SSE2",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 24,
    "sinceExtension": "SSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 24,
    "sinceExtension": "SSSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 24,
    "sinceExtension": "SSE41",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 24,
    "sinceExtension": "SSE42",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 25,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 26,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 27,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 28,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 29,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 30,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "isTwoByte": true,
  },
  {
    "mnem": "NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "MMX",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "SSE1",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "SSE2",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "SSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "SSSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "SSE41",
    "isTwoByte": true,
  },
  {
    "mnem": "HINT_NOP",
    "src": { "@depend": "no", "a": "E", "t": "v" },
    "opcode": 31,
    "sinceExtension": "SSE42",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "R", "t": "d" },
    "src": { "a": "C", "t": "d" },
    "opcode": 32,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "H", "t": "d" },
    "src": { "a": "C", "t": "d" },
    "opcode": 32,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "R", "t": "q" },
    "src": { "a": "C", "t": "q" },
    "opcode": 32,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "H", "t": "q" },
    "src": { "a": "C", "t": "q" },
    "opcode": 32,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "R", "t": "d" },
    "src": { "a": "D", "t": "d" },
    "opcode": 33,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "H", "t": "d" },
    "src": { "a": "D", "t": "d" },
    "opcode": 33,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "R", "t": "q" },
    "src": { "a": "D", "t": "q" },
    "opcode": 33,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "H", "t": "q" },
    "src": { "a": "D", "t": "q" },
    "opcode": 33,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "C", "t": "d" },
    "src": { "a": "R", "t": "d" },
    "opcode": 34,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "C", "t": "d" },
    "src": { "a": "H", "t": "d" },
    "opcode": 34,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "C", "t": "q" },
    "src": { "a": "R", "t": "q" },
    "opcode": 34,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "C", "t": "q" },
    "src": { "a": "H", "t": "q" },
    "opcode": 34,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "D", "t": "d" },
    "src": { "a": "R", "t": "d" },
    "opcode": 35,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "D", "t": "q" },
    "src": { "a": "H", "t": "q" },
    "opcode": 35,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "D", "t": "q" },
    "src": { "a": "R", "t": "q" },
    "opcode": 35,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "D", "t": "q" },
    "src": { "a": "H", "t": "q" },
    "opcode": 35,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "R", "t": "d" },
    "src": { "a": "T", "t": "d" },
    "opcode": 36,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "H", "t": "d" },
    "src": { "a": "T", "t": "d" },
    "opcode": 36,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "T", "t": "d" },
    "src": { "a": "R", "t": "d" },
    "opcode": 38,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOV",
    "dst": { "@depend": "no", "a": "T", "t": "d" },
    "src": { "a": "H", "t": "d" },
    "opcode": 38,
    "modifier": "oszapc",
    "undefinition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOVAPS",
    "dst": { "@depend": "no", "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 40,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVAPD",
    "dst": { "@depend": "no", "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 40,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVAPS",
    "dst": { "@depend": "no", "a": "W", "t": "ps" },
    "src": { "a": "V", "t": "ps" },
    "opcode": 41,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVAPD",
    "dst": { "@depend": "no", "a": "W", "t": "pd" },
    "src": { "a": "V", "t": "pd" },
    "opcode": 41,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPI2PS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "Q", "t": "pi" },
    "opcode": 42,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTSI2SS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "E", "t": "dqp" },
    "opcode": 42,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPI2PD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "Q", "t": "pi" },
    "opcode": 42,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTSI2SD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "E", "t": "dqp" },
    "opcode": 42,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVNTPS",
    "dst": { "@depend": "no", "a": "M", "t": "ps" },
    "src": { "a": "V", "t": "ps" },
    "opcode": 43,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVNTPD",
    "dst": { "a": "M", "t": "pd" },
    "src": { "a": "V", "t": "pd" },
    "opcode": 43,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTTPS2PI",
    "dst": { "a": "P", "t": "pi" },
    "src": { "a": "W", "t": "psq" },
    "opcode": 44,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTTSS2SI",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 44,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTTPD2PI",
    "dst": { "a": "P", "t": "pi" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 44,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTTSD2SI",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 44,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPS2PI",
    "dst": { "a": "P", "t": "pi" },
    "src": { "a": "W", "t": "psq" },
    "opcode": 45,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTSS2SI",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 45,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPD2PI",
    "dst": { "a": "P", "t": "pi" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 45,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTSD2SI",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 45,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PSHUFB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PSHUFB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHADDW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PHADDW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHADDD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PHADDD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHADDSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PHADDSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMADDUBSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PMADDUBSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHSUBW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PHSUBW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHSUBD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PHSUBD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHSUBSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PHSUBSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSIGNB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PSIGNB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSIGNW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PSIGNW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSIGND",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PSIGND",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULHRSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULHRSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PABSB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PABSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PABSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PABSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PABSD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "PABSD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVNTDQA",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "M", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKUSDW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINSD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINUW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINUD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXSD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXUW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXUD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULLD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PHMINPOSUW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 56,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVBE",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "M", "t": "vqp" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "CRC32",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "E", "t": "b" },
    "opcode": 56,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVBE",
    "dst": { "a": "M", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 56,
    "isTwoByte": true,
  },
  {
    "mnem": "CRC32",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 56,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PALIGNR",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 58,
    "isTwoByte": true,
  },
  {
    "mnem": "PALIGNR",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 58,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "DPPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 58,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "DPPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 58,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CMOVO",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 64,
    "isTwoByte": true,
  },
  {
    "mnem": "CMOVNO",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 65,
    "isTwoByte": true,
  },
  {
    "mnem": "CMOVS",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 72,
    "isTwoByte": true,
  },
  {
    "mnem": "CMOVNS",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 73,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVMSKPS",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "U", "t": "ps" },
    "opcode": 80,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVMSKPD",
    "dst": { "a": "G", "t": "dqp" },
    "src": { "a": "U", "t": "pd" },
    "opcode": 80,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "SQRTPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 81,
    "isTwoByte": true,
  },
  {
    "mnem": "SQRTSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 81,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "SQRTPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 81,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "SQRTSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 81,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "RSQRTPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 82,
    "isTwoByte": true,
  },
  {
    "mnem": "RSQRTSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 82,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "RCPPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 83,
    "isTwoByte": true,
  },
  {
    "mnem": "RCPSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 83,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "ANDPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 84,
    "isTwoByte": true,
  },
  {
    "mnem": "ANDPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 84,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "ANDNPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 85,
    "isTwoByte": true,
  },
  {
    "mnem": "ANDNPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 85,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "ORPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 86,
    "isTwoByte": true,
  },
  {
    "mnem": "ORPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 86,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "XORPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 87,
    "isTwoByte": true,
  },
  {
    "mnem": "XORPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 87,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "ADDPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 88,
    "isTwoByte": true,
  },
  {
    "mnem": "ADDSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 88,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "ADDPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 88,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "ADDSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 88,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MULPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 89,
    "isTwoByte": true,
  },
  {
    "mnem": "MULSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 89,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MULPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 89,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MULSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 89,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPS2PD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 90,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPD2PS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 90,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTSS2SD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 90,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTSD2SS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 90,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTDQ2PS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 91,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPS2DQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 91,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTTPS2DQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 91,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "SUBPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 92,
    "isTwoByte": true,
  },
  {
    "mnem": "SUBSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 92,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "SUBPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 92,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "SUBSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 92,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MINPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 93,
    "isTwoByte": true,
  },
  {
    "mnem": "MINSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 93,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MINPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 93,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MINSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 93,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "DIVPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 94,
    "isTwoByte": true,
  },
  {
    "mnem": "DIVSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 94,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "DIVPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 94,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "DIVSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 94,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MAXPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 95,
    "isTwoByte": true,
  },
  {
    "mnem": "MAXSS",
    "dst": { "a": "V", "t": "ss" },
    "src": { "a": "W", "t": "ss" },
    "opcode": 95,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MAXPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 95,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MAXSD",
    "dst": { "a": "V", "t": "sd" },
    "src": { "a": "W", "t": "sd" },
    "opcode": 95,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLBW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 96,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLBW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 96,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLWD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 97,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLWD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 97,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLDQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 98,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 98,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKSSWB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 99,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKSSWB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 99,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 100,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 100,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 101,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 101,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPGTD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 102,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKUSWB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 103,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKUSWB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 103,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHBW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 104,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHBW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 104,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHWD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 105,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHWD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 105,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHDQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 106,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 106,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKSSDW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 107,
    "isTwoByte": true,
  },
  {
    "mnem": "PACKSSDW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 107,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKLQDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 108,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PUNPCKHQDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 109,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "E", "t": "d" },
    "opcode": 110,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "E", "t": "d" },
    "opcode": 110,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVQ",
    "dst": { "@depend": "no", "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 111,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVDQA",
    "dst": { "@depend": "no", "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 111,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVDQU",
    "dst": { "@depend": "no", "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 111,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLW",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 113,
    "sinceExtension": "SSE1",
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLW",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 113,
    "sinceExtension": "SSE1",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAW",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 113,
    "sinceExtension": "SSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAW",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 113,
    "sinceExtension": "SSE3",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLW",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 113,
    "sinceExtension": "SSE41",
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLW",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 113,
    "sinceExtension": "SSE41",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLD",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 114,
    "sinceExtension": "SSE1",
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLD",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 114,
    "sinceExtension": "SSE1",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAD",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 114,
    "sinceExtension": "SSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAD",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 114,
    "sinceExtension": "SSE3",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLD",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 114,
    "sinceExtension": "SSE41",
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLD",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 114,
    "sinceExtension": "SSE41",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLQ",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 115,
    "sinceExtension": "SSE1",
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLQ",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 115,
    "sinceExtension": "SSE1",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLDQ",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 115,
    "sinceExtension": "SSE2",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLQ",
    "dst": { "a": "N", "t": "q" },
    "src": { "a": "I", "t": "b" },
    "opcode": 115,
    "sinceExtension": "SSE41",
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLQ",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 115,
    "sinceExtension": "SSE41",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLDQ",
    "dst": { "a": "U", "t": "dq" },
    "src": { "a": "I", "t": "b" },
    "opcode": 115,
    "sinceExtension": "SSE42",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 116,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 116,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 117,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 117,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 118,
    "isTwoByte": true,
  },
  {
    "mnem": "PCMPEQD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 118,
    "prefix": 102,
    "isTwoByte": true,
  },
  { "mnem": "EMMS", "opcode": 119, "isTwoByte": true },
  {
    "mnem": "VMREAD",
    "dst": { "a": "E", "t": "d" },
    "src": { "a": "G", "t": "d" },
    "opcode": 120,
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "VMREAD",
    "dst": { "a": "E", "t": "q" },
    "src": { "a": "G", "t": "q" },
    "opcode": 120,
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "HADDPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 124,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "HADDPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 124,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "HSUBPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 125,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "HSUBPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 125,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVD",
    "dst": { "@depend": "no", "a": "E", "t": "d" },
    "src": { "a": "P", "t": "q" },
    "opcode": 126,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVD",
    "dst": { "@depend": "no", "a": "E", "t": "d" },
    "src": { "a": "V", "t": "dq" },
    "opcode": 126,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVQ",
    "dst": { "@depend": "no", "a": "V", "t": "q" },
    "src": { "a": "W", "t": "q" },
    "opcode": 126,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVQ",
    "dst": { "@depend": "no", "a": "Q", "t": "q" },
    "src": { "a": "P", "t": "q" },
    "opcode": 127,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVDQA",
    "dst": { "@depend": "no", "a": "W", "t": "dq" },
    "src": { "a": "V", "t": "dq" },
    "opcode": 127,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVDQU",
    "dst": { "@depend": "no", "a": "W", "t": "dq" },
    "src": { "a": "V", "t": "dq" },
    "opcode": 127,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "JO",
    "src": { "a": "J", "t": "vds" },
    "opcode": 128,
    "isTwoByte": true,
  },
  {
    "mnem": "JNO",
    "src": { "a": "J", "t": "vds" },
    "opcode": 129,
    "isTwoByte": true,
  },
  {
    "mnem": "JS",
    "src": { "a": "J", "t": "vds" },
    "opcode": 136,
    "isTwoByte": true,
  },
  {
    "mnem": "JNS",
    "src": { "a": "J", "t": "vds" },
    "opcode": 137,
    "isTwoByte": true,
  },
  {
    "mnem": "SETO",
    "dst": { "@depend": "no", "a": "E", "t": "b" },
    "opcode": 144,
    "isTwoByte": true,
  },
  {
    "mnem": "SETNO",
    "dst": { "@depend": "no", "a": "E", "t": "b" },
    "opcode": 145,
    "isTwoByte": true,
  },
  {
    "mnem": "SETS",
    "dst": { "@depend": "no", "a": "E", "t": "b" },
    "opcode": 152,
    "isTwoByte": true,
  },
  {
    "mnem": "SETNS",
    "dst": { "@depend": "no", "a": "E", "t": "b" },
    "opcode": 153,
    "isTwoByte": true,
  },
  {
    "mnem": "BTS",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 171,
    "modifier": "oszapc",
    "definition": "c",
    "undefinition": "oszap",
    "isTwoByte": true,
  },
  {
    "mnem": "LDMXCSR",
    "src": { "a": "M", "t": "d" },
    "opcode": 174,
    "sinceExtension": "SSE1",
    "isTwoByte": true,
  },
  {
    "mnem": "STMXCSR",
    "dst": { "a": "M", "t": "d" },
    "opcode": 174,
    "sinceExtension": "SSE2",
    "isTwoByte": true,
  },
  {
    "mnem": "LFENCE",
    "opcode": 174,
    "sinceExtension": "SSSE3",
    "isTwoByte": true,
  },
  {
    "mnem": "MFENCE",
    "opcode": 174,
    "sinceExtension": "SSE41",
    "isTwoByte": true,
  },
  {
    "mnem": "SFENCE",
    "opcode": 174,
    "sinceExtension": "SSE42",
    "isTwoByte": true,
  },
  {
    "mnem": "CLFLUSH",
    "src": { "@depend": "no", "a": "M", "t": "b" },
    "opcode": 174,
    "sinceExtension": "SSE42",
    "isTwoByte": true,
  },
  {
    "mnem": "IMUL",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 175,
    "modifier": "oszapc",
    "definition": "oc",
    "undefinition": "szap",
    "isTwoByte": true,
  },
  {
    "mnem": "BTR",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 179,
    "modifier": "oszapc",
    "definition": "c",
    "undefinition": "oszap",
    "isTwoByte": true,
  },
  {
    "mnem": "MOVZX",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "b" },
    "opcode": 182,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVZX",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "w" },
    "opcode": 183,
    "isTwoByte": true,
  },
  { "mnem": "JMPE", "opcode": 184, "isTwoByte": true },
  {
    "mnem": "POPCNT",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 184,
    "modifier": "oszapc",
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "BTS",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "I", "t": "b" },
    "opcode": 186,
    "sinceExtension": "SSSE3",
    "modifier": "oszapc",
    "definition": "c",
    "undefinition": "oszap",
    "isTwoByte": true,
  },
  {
    "mnem": "BTR",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "I", "t": "b" },
    "opcode": 186,
    "sinceExtension": "SSE41",
    "modifier": "oszapc",
    "definition": "c",
    "undefinition": "oszap",
    "isTwoByte": true,
  },
  {
    "mnem": "BTC",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "I", "t": "b" },
    "opcode": 186,
    "sinceExtension": "SSE42",
    "modifier": "oszapc",
    "definition": "c",
    "undefinition": "oszap",
    "isTwoByte": true,
  },
  {
    "mnem": "BTC",
    "dst": { "a": "E", "t": "vqp" },
    "src": { "a": "G", "t": "vqp" },
    "opcode": 187,
    "modifier": "oszapc",
    "definition": "c",
    "undefinition": "oszap",
    "isTwoByte": true,
  },
  {
    "mnem": "BSF",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 188,
    "modifier": "oszapc",
    "definition": "z",
    "undefinition": "osapc",
    "isTwoByte": true,
  },
  {
    "mnem": "BSR",
    "dst": { "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "vqp" },
    "opcode": 189,
    "modifier": "oszapc",
    "definition": "z",
    "undefinition": "osapc",
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSX",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "b" },
    "opcode": 190,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVSX",
    "dst": { "@depend": "no", "a": "G", "t": "vqp" },
    "src": { "a": "E", "t": "w" },
    "opcode": 191,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVNTI",
    "dst": { "@depend": "no", "a": "M", "t": "dqp" },
    "src": { "a": "G", "t": "dqp" },
    "opcode": 195,
    "isTwoByte": true,
  },
  {
    "mnem": "VMPTRLD",
    "src": { "a": "M", "t": "q" },
    "opcode": 199,
    "sinceExtension": "SSE41",
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "VMCLEAR",
    "dst": { "a": "M", "t": "q" },
    "opcode": 199,
    "sinceExtension": "SSE41",
    "modifier": "oszapc",
    "definition": "oszapc",
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "VMXON",
    "src": { "a": "M", "t": "q" },
    "opcode": 199,
    "sinceExtension": "SSE41",
    "modifier": "oszapc",
    "definition": "oszapc",
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "VMPTRST",
    "dst": { "a": "M", "t": "q" },
    "opcode": 199,
    "sinceExtension": "SSE42",
    "modifier": "oszapc",
    "definition": "oszapc",
    "isTwoByte": true,
  },
  {
    "mnem": "BSWAP",
    "dst": { "a": "Z", "t": "vqp" },
    "opcode": 200,
    "isTwoByte": true,
  },
  {
    "mnem": "ADDSUBPD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 208,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "ADDSUBPS",
    "dst": { "a": "V", "t": "ps" },
    "src": { "a": "W", "t": "ps" },
    "opcode": 208,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 209,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 209,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 210,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 210,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 211,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRLQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 211,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 212,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 212,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULLW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 213,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULLW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 213,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVQ",
    "dst": { "a": "W", "t": "q" },
    "src": { "a": "V", "t": "q" },
    "opcode": 214,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVQ2DQ",
    "dst": { "@depend": "no", "a": "V", "t": "dq" },
    "src": { "a": "N", "t": "q" },
    "opcode": 214,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVDQ2Q",
    "dst": { "@depend": "no", "a": "P", "t": "q" },
    "src": { "a": "U", "t": "q" },
    "opcode": 214,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PMOVMSKB",
    "dst": { "@depend": "no", "a": "G", "t": "dqp" },
    "src": { "a": "N", "t": "q" },
    "opcode": 215,
    "isTwoByte": true,
  },
  {
    "mnem": "PMOVMSKB",
    "dst": { "@depend": "no", "a": "G", "t": "dqp" },
    "src": { "a": "U", "t": "dq" },
    "opcode": 215,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBUSB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 216,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBUSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 216,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBUSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 217,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBUSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 217,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINUB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 218,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINUB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 218,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PAND",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 219,
    "isTwoByte": true,
  },
  {
    "mnem": "PAND",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 219,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDUSB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 220,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDUSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 220,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDUSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 221,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDUSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 221,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXUB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 222,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXUB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 222,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PANDN",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 223,
    "isTwoByte": true,
  },
  {
    "mnem": "PANDN",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 223,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PAVGB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 224,
    "isTwoByte": true,
  },
  {
    "mnem": "PAVGB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 224,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 225,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 225,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 226,
    "isTwoByte": true,
  },
  {
    "mnem": "PSRAD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 226,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PAVGW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 227,
    "isTwoByte": true,
  },
  {
    "mnem": "PAVGW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 227,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULHUW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 228,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULHUW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 228,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULHW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 229,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULHW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 229,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTPD2DQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 230,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTTPD2DQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "pd" },
    "opcode": 230,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "CVTDQ2PD",
    "dst": { "a": "V", "t": "pd" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 230,
    "prefix": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVNTQ",
    "dst": { "@depend": "no", "a": "M", "t": "q" },
    "src": { "a": "P", "t": "q" },
    "opcode": 231,
    "isTwoByte": true,
  },
  {
    "mnem": "MOVNTDQ",
    "dst": { "@depend": "no", "a": "M", "t": "dq" },
    "src": { "a": "V", "t": "dq" },
    "opcode": 231,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBSB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 232,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 232,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 233,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 233,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 234,
    "isTwoByte": true,
  },
  {
    "mnem": "PMINSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 234,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "POR",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 235,
    "isTwoByte": true,
  },
  {
    "mnem": "POR",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 235,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDSB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 236,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDSB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 236,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 237,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 237,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXSW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 238,
    "isTwoByte": true,
  },
  {
    "mnem": "PMAXSW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 238,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PXOR",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 239,
    "isTwoByte": true,
  },
  {
    "mnem": "PXOR",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 239,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "LDDQU",
    "dst": { "@depend": "no", "a": "V", "t": "dq" },
    "src": { "a": "M", "t": "dq" },
    "opcode": 240,
    "prefix": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 241,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 241,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 242,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 242,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 243,
    "isTwoByte": true,
  },
  {
    "mnem": "PSLLQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 243,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULUDQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 244,
    "isTwoByte": true,
  },
  {
    "mnem": "PMULUDQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 244,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PMADDWD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "d" },
    "opcode": 245,
    "isTwoByte": true,
  },
  {
    "mnem": "PMADDWD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 245,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSADBW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 246,
    "isTwoByte": true,
  },
  {
    "mnem": "PSADBW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 246,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 248,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 248,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 249,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 249,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 250,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 250,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBQ",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 251,
    "isTwoByte": true,
  },
  {
    "mnem": "PSUBQ",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 251,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDB",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 252,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDB",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 252,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDW",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 253,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDW",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 253,
    "prefix": 102,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDD",
    "dst": { "a": "P", "t": "q" },
    "src": { "a": "Q", "t": "q" },
    "opcode": 254,
    "isTwoByte": true,
  },
  {
    "mnem": "PADDD",
    "dst": { "a": "V", "t": "dq" },
    "src": { "a": "W", "t": "dq" },
    "opcode": 254,
    "prefix": 102,
    "isTwoByte": true,
  },
];
